/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem { 'productId' : bigint, 'quantity' : bigint }
export type PaymentMethod = { 'upi' : string } |
  { 'cashOnDelivery' : null };
export interface Product {
  'id' : bigint,
  'reviews' : Array<string>,
  'name' : string,
  'description' : string,
  'category' : string,
  'price' : number,
}
export interface _SERVICE {
  'addProduct' : ActorMethod<[string, string, number, string], bigint>,
  'addReview' : ActorMethod<[bigint, string], undefined>,
  'addToCart' : ActorMethod<[bigint, bigint], undefined>,
  'calculateTotal' : ActorMethod<[], number>,
  'checkout' : ActorMethod<[PaymentMethod], string>,
  'searchProducts' : ActorMethod<[string], Array<Product>>,
  'viewCart' : ActorMethod<[], Array<CartItem>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];